name: .NET

on:
  push:
    branches: [ main, workflow_dispatch ]

env:
  IIS_WEBAPP_NAME: BlazorUX
  WORKING_DIRECTORY: backend/aspnetcore
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: GitHub Actions WebDeploy
      # You may pin to the exact commit or the version.
      # uses: cschleiden/webdeploy-action@48a2cdaf8aaa2bc762c12948ada3db14faead320
      uses: cschleiden/webdeploy-action@v1.1.0
        with:
          # Name of an existing website on the IIS machine
          webSiteName:
            description: 'VenusTex'
            required: true
          package:
            description: '/publish'
            required: true
